<template>
<v-container>
    <p>Not sure how the email will work, but on the santaSetup it will call this template, which will take in the full object as a prop and send the emails</p>
    <div v-if="error">
    <ErrorPopUpModal :value=returnObject />
    </div>
</v-container>
</template>
<script>
import ErrorPopUpModal from './ErrorPopUpModal.vue';

export default ({
    //value will be who sends what to who, generated by santa setup
    props: value,
    components: {
        ErrorPopUpModal
    },
    data() {
        return {
            error: 'this will actually be a boolean to show if there was an error or not if there is an error, use a v-if on the error pop up modal and pass in teh error as a prop',
            returnObject: 'who knows what will be returned from sending the emails, this is the object that will be passed to the error modal'
        }
    },
    methods: {
        sendEmails(){
            //this is where teh email will actually be sent, set a data value to get in the return value
        },
        checkReturn(){
            //some sort of function to check the return on what the email extension returns, this will call on 
            //the error pop up and pass in a prop to that as well
            //this changes the error boolean, if error set to true, show the modal, and emit to santasetup that stuff needs to be regenerated
            //emitting is kind of complicated, but this will call to the parent function that hey somethin went wrong and here is my object that says why
            this.$emit('failure', returnObject);
        }
    }
})
</script>
