<template>
<v-container>
    <p>Not sure how the email will work, but on the santaSetup it will call this template, which will take in the full object as a prop and send the emails</p>
</v-container>
</template>
<script>
export default ({
    //value will be who sends what to who, generated by santa setup
    props: ['value'],
    data() {
        return {
            returnObject: {email: 'bademail@email.com'}
        }
    },
    methods: {
        sendEmails(){
            //this is where teh email will actually be sent, set a data value to get in the return value
        },
        checkReturn(){
            //some sort of function to check the return on what the email extension returns, this will call on 
            //the error pop up and pass in a prop to that as well
            //this changes the error boolean, if error set to true, show the modal, and emit to santasetup that stuff needs to be regenerated
            //emitting is kind of complicated, but this will call to the parent function that hey somethin went wrong and here is my object that says why
            this.$emit('failure', this.returnObject);
        }
    },
    mounted(){
        this.checkReturn();
    }
})
</script>
