<template>
<v-container>
    <p>Not sure how the email will work, but on the santaSetup it will call this template, which will take in the full object as a prop and send the emails</p>
    <div v-if="error">
    <ErrorPopUpModal :value=returnObject />
    </div>
</v-container>
</template>


<script type="text/javascript">

import ErrorPopUpModal from './ErrorPopUpModal.vue';
import emailjs from '@emailjs/browser';

emailjs.init("user_EAOcZjTlgI1klK7aFHxW3");

export default ({
    //value will be who sends what to who, generated by santa setup
    props: ['tName','tEmail','gMsg','aName','aMsg'],
    components: {
        ErrorPopUpModal
    },
    data() {
        return {
            error: 'this will actually be a boolean to show if there was an error or not if there is an error, use a v-if on the error pop up modal and pass in teh error as a prop',
            returnObject: 'who knows what will be returned from sending the emails, this is the object that will be passed to the error modal'
        }
    },
    methods: {
        sendEmail(e){
            //this is where teh email will actually be sent, set a data value to get in the return value
            try {
                emailjs.sendForm('service_u6y98dj', 'template_h8111ee', e.target,
                'user_EAOcZjTlgI1klK7aFHxW3', {
                to_name: this.tName,
                to_email: this.tEmail,
                general_message: this.gMsg,
                assigned_name: this.aName,
                assigned_details: this.aMsg
                })

            } catch(error) {
                console.log({error})
            }
        },
        checkReturn(){
            //some sort of function to check the return on what the email extension returns, this will call on 
            //the error pop up and pass in a prop to that as well
            //this changes the error boolean, if error set to true, show the modal, and emit to santasetup that stuff needs to be regenerated
            //emitting is kind of complicated, but this will call to the parent function that hey somethin went wrong and here is my object that says why
            this.$emit('failure', this.returnObject);
        }
    }
})

</script>


